// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAPI.Repository.Database;

#nullable disable

namespace TestAPI.Repository.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestAPI.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hall");
                });

            modelBuilder.Entity("TestAPI.Models.Reserved", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HallObjId")
                        .HasColumnType("int");

                    b.Property<bool>("booked")
                        .HasColumnType("bit");

                    b.Property<int>("seatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallObjId");

                    b.ToTable("Reserved");
                });

            modelBuilder.Entity("TestAPI.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("SeatCol")
                        .HasColumnType("int");

                    b.Property<int>("SeatRow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("TestAPI.Models.Reserved", b =>
                {
                    b.HasOne("TestAPI.Models.Hall", "HallObj")
                        .WithMany()
                        .HasForeignKey("HallObjId");

                    b.Navigation("HallObj");
                });

            modelBuilder.Entity("TestAPI.Models.Seat", b =>
                {
                    b.HasOne("TestAPI.Models.Hall", null)
                        .WithMany("Seat")
                        .HasForeignKey("HallId");
                });

            modelBuilder.Entity("TestAPI.Models.Hall", b =>
                {
                    b.Navigation("Seat");
                });
#pragma warning restore 612, 618
        }
    }
}
